Blog_Django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from article import views

urlpatterns = [
    path('admin/', admin.site.urls, name = 'admin'),
    path('', views.index, name = 'index'),
    path('about/', views.about, name = 'about'),
    
    path('articles/', include('article.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('dashboard/', views.dashboard, name = 'dashboard'),
    path('addarticle/', views.addArticle, name = 'addarticle'),
    path('', views.articles, name = 'articles'),
    path('article/<slug:slug>', views.detail, name = 'detail'),
    path('update/<slug:slug>', views.update, name = 'update'),
    path('delete/<int:id>', views.delete, name = 'delete'),
    path('comment/<slug:slug>', views.addComment, name = 'comment'),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.register, name = 'register'),
    path('login/', views.loginUser, name = 'login'),
    path('logout/', views.logoutUser, name = 'logout'),
]

templates/includes/footer.html
    <hr>    
    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              {% if request.user.is_authenticated %}
                <li class="list-inline-item">
                    <a href="https://www.linkedin.com/in/melik%C5%9Fah-bilir-9b76b391/" target="_blank">
                    <span class="fa-stack fa-lg">
                        <i class="fas fa-circle fa-stack-2x"></i>
                        <i class="fab fa-linkedin fa-stack-1x fa-inverse"></i>
                    </span>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="https://github.com/MeliksahBilir" target="_blank">
                    <span class="fa-stack fa-lg">
                        <i class="fas fa-circle fa-stack-2x"></i>
                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                    </span>
                    </a>
                </li>
                {% else %}
                    <li class="list-inline-item">
                        <a href="{% url 'index' %}">
                        <span class="fa-stack fa-lg">
                            <i class="fas fa-circle fa-stack-2x"></i>
                            <i class="fab fa-linkedin fa-stack-1x fa-inverse"></i>
                        </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="{% url 'index' %}">
                        <span class="fa-stack fa-lg">
                            <i class="fas fa-circle fa-stack-2x"></i>
                            <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                        </span>
                        </a>
                    </li>
                {% endif %}
            </ul>
            <p class="copyright text-muted">Copyright &copy; Your Website 2018</p>
          </div>
        </div>
      </div>
    </footer>
    

templates/includes/header.html
    <!-- Page Header -->
    <header class="masthead" style="background-image: url('/media/header.png'); ">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>Django</h1>
              <span class="subheading">Python</span>
            </div>
          </div>
        </div>
      </div>
    </header>

templates/includes/navbar.html
<style>
    #lock-icon{
        font-size: 15px;
        color: #FFFFFF;
        margin-left: -15px;
        margin-bottom: -35px;
        display: inline-block;
    }
</style>   
       
    <!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">Blog - Django</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <form class="navbar-form" role="search">
        <div class="input-group">
            {% csrf_token %}
            <input style="height:32px; width:auto" type="text" class="form-control" placeholder="Arama Yap" name="q">
            <div class="input-group-btn">
                <button style="height:30px; width:30px" class="btn btn-secondary" type="submit"><i class="fas fa-search" style="height:30px; width:30px" id="lock-icon"></i></button>
            </div>
        </div>
        </form>
        <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">Hakkımda</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'article:articles' %}">Makaleler</a>
        </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'article:dashboard' %}">Kontrol Paneli</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin Paneli</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'user:logout' %}">Çıkış Yap</a>
                </li>
            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'user:register' %}">Kayıt Ol</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'user:login' %}">Giriş Yap</a>
                </li>
            {% endif %}
        </ul>
    </div>
    </div>
</nav>