Blog_Django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from article import views

urlpatterns = [
    path('admin/', admin.site.urls, name = 'admin'),
    path('', views.index, name = 'index'),
    path('about/', views.about, name = 'about'),
    
    path('articles/', include('article.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('dashboard/', views.dashboard, name = 'dashboard'),
    path('addarticle/', views.addArticle, name = 'addarticle'),
    path('', views.articles, name = 'articles'),
    path('article/<slug:slug>', views.detail, name = 'detail'),
    path('update/<slug:slug>', views.update, name = 'update'),
    path('delete/<int:id>', views.delete, name = 'delete'),
    path('comment/<slug:slug>', views.addComment, name = 'comment'),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.register, name = 'register'),
    path('login/', views.loginUser, name = 'login'),
    path('logout/', views.logoutUser, name = 'logout'),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User", verbose_name="Kullanici Adi :", on_delete=models.CASCADE)
    title = models.CharField(verbose_name="Başlık :", max_length=50)
    content = RichTextField(verbose_name="İçerik :")
    image = models.FileField(blank=True, null=True, verbose_name='Eklenecek dosyayı seçiniz :')
    slug = models.SlugField(unique=True, editable=False, max_length=60)
    created_date = models.DateTimeField(verbose_name="Yayinlanma Tarihi :", auto_now_add=True)

    def __str__(self):
        return self.title
    
    def get_unique_slug(self):
        slug = slugify(self.title.replace('ı','i'))
        unique_slug = slug
        counter = 1 
        while Article.objects.filter(slug = unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, counter)
            counter += 1
        return unique_slug

    def save(self, *args, **kwargs):
        self.slug = self.get_unique_slug()
        return super(Article, self).save(args, **kwargs)
    
    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name = 'Makale', related_name = 'comments')
    comment_author = models.CharField(max_length = 50, verbose_name = 'Kullanıcı Adı :')
    comment_content = models.TextField(verbose_name = 'Yorum :')
    comment_date = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content', 'image']
    

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse
from django.template import Template, Context
from .forms import ArticleForm
from .models import Article, Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

# Create your views here.

def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def articles(request):
    query = request.GET.get('q')
    if query:
        articles = Article.objects.filter(title__contains = query)
        paginator = Paginator(articles, 4)
        page = request.GET.get('page')
        articles = paginator.get_page(page)
        return render(request, 'articles.html', {'articles' : articles})

    articles = Article.objects.all()
    paginator = Paginator(articles, 4)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    return render(request, 'articles.html', {'articles' : articles})

@login_required(login_url = 'user:login')
def dashboard(request):
    articles = Article.objects.filter(author=request.user)
    context = {
        'articles' : articles
    }
    return render(request, 'dashboard.html', context)

@login_required(login_url = 'user:login')
def detail(request, slug):
    article = get_object_or_404(Article, slug = slug)
    comments = article.comments.all()
    context = {
        'article' : article,
        'comments' : comments
    }
    return render(request, 'detail.html', context)

@login_required(login_url = 'user:login')
def update(request, slug):
    article = get_object_or_404(Article, slug = slug)
    form = ArticleForm(request.POST or None, request.FILES or None, instance = article)
    if form.is_valid():

        article = form.save(commit = False)
        article.author = request.user
        article.save()

        messages.success(request, 'Makale GÜncellendi...')
        return redirect('article:dashboard')

    context = {
        'form' : form
    }

    return render(request, 'update.html', context)

@login_required(login_url = 'user:login')
def delete(request, id):
    article = get_object_or_404(Article, id = id)
    article.delete()
    messages.success(request, 'Makaleniz Silindi...')
    # index disinda bir yere gitmek icin
    return redirect('article:dashboard')

@login_required(login_url = 'user:login')
def addArticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
       
        article = form.save(commit = False)
        article.author = request.user
        article.save()

        messages.success(request, 'Makale Oluşturuldu...')
        return redirect('article:dashboard')

    context = {'form' : form}
    return render(request, 'addarticle.html', context)

@login_required(login_url = 'user:login')
def addComment(request, slug):
    article = get_object_or_404(Article, slug = slug)

    if request.method == 'POST':
        comment_author = request.POST.get('comment_author')
        comment_content = request.POST.get('comment_content')
        
        newComment = Comment(comment_author = comment_author, comment_content = comment_content)
        # yorum yazilacak makaleyi id si cekip Comment model de foreign key ile baglama islemi
        newComment.article = article
        newComment.save()
        
    return redirect(reverse('article:detail', kwargs={'slug':slug}))

templates/about.html
{% extends "layout.html" %}

{% block body %}
  <h3>Hakkımda</h3>
  <hr>
    Ben Melikşah Bilir. Django ile Python temelli web tasarım yapmaya çalışıyorum.
  <hr>
{% endblock %}

templates/addarticle.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}

    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h3>Makale Ekle</h3>
            <hr>            
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form|crispy }}
                <button type="submit" class="btn btn-info">Makale Ekle</button>
            </form>
        </div>
    </div>

{% endblock  %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}
    
    <h3>Makaleler</h3>
    <hr>
    <!-- Main Widgets Column -->
    <div class="row">
        <div class="col-lg-8 offset-md-2">
            {% if articles %}
                {% for article in articles %}
                    <!-- Title -->
                    <a href="{% url 'article:detail' article.slug %}"> 
                        <h2 class="mt-4"> {{ article.title|safe }} </h2>
                    </a>
                    <!-- Author -->
                    <p class="lead">
                        {{ article.author|safe }} tarafından yayınlandı.
                    </p>
                    <!-- Date/Time -->
                    <p> {{ article.created_date }} </p>
                    <!-- Preview Image -->
                    {% if article.image %}
                        <a href="{% url 'article:detail' article.slug %}"> 
                            <img class="img-fluid rounded" src="{{ article.image.url }}">
                        </a>
                    {% endif %}
                    <!-- Post Content -->
                    <p class="lead">
                        {{ article.content|safe|truncatewords:20 }}
                    </p>
                    <hr>
                {% endfor %}
            {% else %}
                <div class="alert alert-danger"> Bu blogta herhangi bir makale bulunmuyor !!! </div>
            {% endif %}
        </div>
    </div>
    <div class="text-center">
        <span class="step-links">
            {% if articles.has_previous %}
                <a class="fa fa-angle-double-left" href="?page=1"></a>
                <a class="fa fa-angle-left" href="?page={{ articles.previous_page_number }}"></a>
            {% else %}
                <a class="fa fa-angle-double-left"></a>
                <a class="fa fa-angle-left"></a>
            {% endif %}
            <span style="color:gray" class="current">
                Sayfa {{ articles.number }} - {{ articles.paginator.num_pages }}.
            </span>
            {% if articles.has_next %}
                <a class="fa fa-angle-right" href="?page={{ articles.next_page_number }}"></a>
                <a class="fa fa-angle-double-right" href="?page={{ articles.paginator.num_pages }}"></a>
            {% else %}
                <a class="fa fa-angle-right"></a>
                <a class="fa fa-angle-double-right"></a>
            {% endif %}
        </span>
    </div>
    
{% endblock  %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

    <h3>Kontrol Paneli</h3>
    <hr>
    <p>
        Hoşgeldiniz, <strong> {{ request.user.username }} </strong>
    </p>
    <hr>
    <a class="btn btn-info" href="{% url 'article:addarticle' %}">Makale Ekle</a>
    <hr>
    {% if articles %}
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                <th class="th-sm text-center" scope="col">Başlık</th>
                <th class="th-sm text-center" scope="col">Tarih</th>
                <th class="th-sm text-center" scope="col">İşlemler</th>
                </tr>
            </thead>
            <tbody>
                {% for article in articles %}
                    <tr>
                        <td class="th-sm text-center align-middle"> <a href="{% url 'article:detail' article.slug %}"> {{ article.title }} </a> </td>
                        <td class="th-sm text-center align-middle"> {{ article.created_date }} </td>
                        <td class="th-sm text-center align-middle"> <a href="{% url 'article:update' article.slug %}" class="btn btn-info"> Güncelle </a> &nbsp; <a href="{% url 'article:delete' article.id %}" class="btn btn-danger"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sil &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </a> </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
        <div class="alert alert-danger"> Henüz bir makaleniz bulunmuyor</div>
    {% endif %}
    

{% endblock  %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}

    <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">
        <!-- Title -->
        <h3 class="mt-4"> {{ article.title|safe }} </h3>
        <!-- Author -->
        <p class="lead">
            by {{ article.author|safe }}
        </p>
        <hr>
        <!-- Date/Time -->
        <p> {{ article.created_date }} </p>
        <hr>
        <!-- Preview Image -->
        {% if article.image %}
            <img class="img-fluid rounded" src="{{ article.image.url }}">
            <hr>
        {% endif %}
        <!-- Post Content -->
        <p class="lead">
            {{ article.content|safe }}
        </p>
        <hr>
        <h4>Yorumlar</h4>
        <br>
        {% if comments %}
            {% for comment in comments %}
                <!-- Single Comment -->
                <div class="media mb-4">
                        <img class="d-flex mt-1 mr-3 rounded-circle" src="http://placehold.it/50x50">
                        <div class="media-body">
                        <h5 class="mt-0">{{ comment.comment_author }} <small>{{ comment.comment_date|timesince }}</small></h5>
                            {{ comment.comment_content }}
                            <hr>
                        </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="alert alert-danger">
                Bu makaleye yorum yapılmamış...
                <strong>İlk yorum yapan siz olun!!!</strong>
            </div>
        {% endif %}

        <!-- Comments Form -->
        <div class="card my-4">
            <h5 class="card-header">Yorum Ekle :</h5>
            <div class="card-body">
            <form action="{% url 'article:comment' article.slug %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleInputEmail1">İsim : </label>
                    <input name = 'comment_author' type="text" class="form-control">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Yorumunuz : </label>
                    <textarea name = 'comment_content' class="form-control" rows="8"></textarea>
                </div>
                <button type="submit" style="float:right" class="btn btn-outline-info">Ekle</button>
            </form>
            </div>
        </div>
    </div>

{% endblock  %}

templates/index.html
{% extends "layout.html" %}

{% block body %}
    <!-- Main Content -->
    <div class="row">
        <div class="col-lg-10 col-md-10 mx-auto">
            <div class="post-preview">
                <h2 class="post-title text-center">
                    Melikşah Bilir
                </h2>
                <p class="post-subtitle text-center">
                    Python ve Django bilgilerimi kullanarak hazırlamış olduğum bu demo sitede gezinebilmek için 
                    gerekli kullanıcı adı ve şifre bilgileri aşağıdaki gibidir.
                    <br>
                    <strong>Kullanıcı Adı : rootUser</strong>
                    <br>
                    <strong>Şifre : toor0124</strong>
                </p>
            </div>            
        </div>
    </div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django - Blog</title>

    <link rel="shortcut icon" type="image/png" href="/media/favicon.png"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'ckeditor/ckeditor/plugins/codesnippet/lib/highlight/styles/default.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}" type="text/css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' type='text/css'>
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' type='text/css'>

</head>
<body>
    <!-- Navbar -->
    {% include "includes/navbar.html" %}
    {% include "includes/header.html" %}

    <div class="container">
        <!-- Messages -->
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'info' %}
                    <div class="alert alert-danger">{{ message }}</div>
                {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}
        <!-- Body -->
        {% block body %}
        
        {% endblock  %}
    </div>

    {% include "includes/footer.html" %}

    <script src="{% static 'ckeditor/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js' %}"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/clean-blog.min.js' %}"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Giriş Yap</h3>
            <hr>            
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-info">Giriş Yap</button>
            </form>
        </div>
    </div>

{% endblock  %}

templates/register.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Kayıt Ol</h3>
            <hr>            
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-info">Kayıt Ol</button>
            </form>
        </div>
    </div>

{% endblock  %}

templates/update.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}

    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h3>Makale Güncelle</h3>
            <hr>            
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form|crispy }}
                <button type="submit" class="btn btn-info">Makale Güncelle</button>
            </form>
        </div>
    </div>

{% endblock  %}